name: Demo GH Action

on: [push]

jobs:
  demo:
    name: demo
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [18.x]
        os: [ubuntu-latest]
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm install
      - run: npm run mocha-junit
        continue-on-error: true
      - uses: yatt-ai/yatt-pipe-action@main
        with:
          source: junit:results/mocha-results.xml
          target: yatt
        env:
          YATT_TARGET_CREDENTIALS: '{"target":{"token":"yatt_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX","base_url":"https://app.yatt.ai/"}}'
